#!/bin/bash

# Dream More Admin Panel - Setup & Configuration Guide

echo "🔐 Admin Panel Setup"
echo "=================="
echo ""
echo "1. Set Admin Password (Environment Variable)"
echo "   Add to .env.local or deploy settings:"
echo "   NEXT_PUBLIC_ADMIN_PASSWORD=your_secure_password_here"
echo ""
echo "2. Default Password (if not set)"
echo "   Username: admin"
echo "   Password: admin123"
echo ""
echo "3. Access Admin Panel"
echo "   URL: http://localhost:3000/admin/login"
echo ""
echo "4. Login"
echo "   - Enter admin password"
echo "   - Session expires after 24 hours"
echo "   - Click 'Access Admin Panel' button"
echo ""
echo "5. Features Available After Login"
echo "   ✓ Dashboard - Overview statistics"
echo "   ✓ Manage Courses - Add/Edit/Delete courses"
echo "   ✓ Bulk Add Courses - Add multiple courses at once"
echo "   ✓ Registrations - View and manage student data"
echo "   ✓ Settings - Configure system settings"
echo ""
echo "6. Bulk Course Addition"
echo "   - Navigate to 'Manage Courses' page"
echo "   - Click 'Bulk Add Courses' button"
echo "   - Enter course names (one per line)"
echo "   - Optional: Use 'CODE: Course Name' format"
echo "   - Click 'Add All Courses'"
echo ""
echo "7. Logout"
echo "   - Click 'Logout' button in sidebar"
echo "   - You'll be redirected to login page"
echo ""
echo "✅ Admin panel is now ready to use!"
